# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Kategorie',
            field=models.CharField(choices=[('Blu-ray', 'Blu-ray'), ('Geschirr', 'Geschirr'), ('DVD', 'DVD')], default='', max_length=400),
        ),
    ]
